"""empty message

Revision ID: 549840bce0ac
Revises: e80c68b1abd
Create Date: 2014-08-18 19:55:41.806750

"""

# revision identifiers, used by Alembic.
revision = '549840bce0ac'
down_revision = 'e80c68b1abd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    ### end Alembic commands ###
